from app.routers.auth import auth_router
from app.routers.user import user_router
from app.routers.guitar import guitar_router
from app.routers.order import order_router
from app.routers.order_product import order_product_router
from app.routers.cart import cart_product_router
from app.routers.combo_ampf import combo_router
from app.routers.effect import effect_router
from app.routers.processor import processor_router