"""add_delete_casade_to_cp

Revision ID: 3012909d87d6
Revises: 66b107c023cb
Create Date: 2025-07-01 08:01:32.479863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3012909d87d6'
down_revision: Union[str, None] = '66b107c023cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'])
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
