"""update fkeys2

Revision ID: 4bfafc15438c
Revises: 97bf2f8f1bc3
Create Date: 2025-07-02 11:11:47.534776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bfafc15438c'
down_revision: Union[str, None] = '97bf2f8f1bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_product_order_id_fkey1', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_product_guitar_id_fkey', 'order_product', 'guitar', ['guitar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'])
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'])
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'])
    op.create_foreign_key('order_product_order_id_fkey1', 'order_product', 'order', ['order_id'], ['id'])
    op.drop_constraint('order_product_guitar_id_fkey', 'order_product', type_='foreignkey')
    # ### end Alembic commands ###
