"""update fkeys

Revision ID: 66b107c023cb
Revises: 2086f4efed5c
Create Date: 2025-06-30 12:52:15.699944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b107c023cb'
down_revision: Union[str, None] = '2086f4efed5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'cart_user_id_fkey',
        'cart',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'cart_user_id_fkey',  # Новое имя (может быть таким же)
        'cart',  # Таблица где находится ключ
        'user',  # Таблица на которую ссылается
        ['user_id'],   # Колонка с ключом
        ['id'],          # Колонка на которую ссылается
        ondelete='CASCADE'  # Каскадное удаление
    )
    op.drop_constraint(
        'order_user_id_fkey',
        'order',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'order_user_id_fkey',  # Новое имя (может быть таким же)
        'order',  # Таблица где находится ключ
        'user',  # Таблица на которую ссылается
        ['user_id'],   # Колонка с ключом
        ['id'],          # Колонка на которую ссылается
        ondelete='CASCADE'  # Каскадное удаление
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'cart_user_id_fkey',
        'cart',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'cart_user_id_fkey',  # Новое имя (может быть таким же)
        'cart',  # Таблица где находится ключ
        'user',  # Таблица на которую ссылается
        ['user_id'],   # Колонка с ключом
        ['id']          # Колонка на которую ссылается
    )
    op.drop_constraint(
        'order_user_id_fkey',
        'order',
        type_='foreignkey'
    )
    op.create_foreign_key(
        'order_user_id_fkey',  # Новое имя (может быть таким же)
        'order',  # Таблица где находится ключ
        'user',  # Таблица на которую ссылается
        ['user_id'],   # Колонка с ключом
        ['id']          # Колонка на которую ссылается
    )
    # ### end Alembic commands ###
