"""new_migr

Revision ID: 6ff5ea5049d8
Revises: c2ad70b57e6b
Create Date: 2026-05-20 14:53:55.784274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff5ea5049d8'
down_revision: Union[str, None] = 'c2ad70b57e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key(None, 'cart_product', 'cart', ['cart_id'], ['id'])
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'order', ['order_id'], ['id'])
    op.alter_column('user', 'passhash',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'passhash',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
