"""update op fkeys

Revision ID: 97bf2f8f1bc3
Revises: 3012909d87d6
Create Date: 2025-07-02 10:53:32.768397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bf2f8f1bc3'
down_revision: Union[str, None] = '3012909d87d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'])
    op.drop_constraint('cart_product_guitar_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_constraint('cart_product_processor_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_constraint('cart_product_effect_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_constraint('cart_product_combo_id_fkey', 'cart_product', type_='foreignkey')
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_effect_id_fkey', 'cart_product', 'effect_pedal', ['effect_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'])
    op.create_foreign_key('cart_product_combo_id_fkey', 'cart_product', 'combo_amplifier', ['combo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('cart_product_guitar_id_fkey', 'cart_product', 'guitar', ['guitar_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('cart_product_processor_id_fkey', 'cart_product', 'processor', ['processor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint('order_product_processor_id_fkey', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_combo_id_fkey', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_effect_id_fkey', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_order_id_fkey', 'order_product', type_='foreignkey')
    op.drop_constraint('order_product_guitar_id_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'guitar', ['guitar_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('order_product_effect_id_fkey', 'order_product', 'effect_pedal', ['effect_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('order_product_processor_id_fkey', 'order_product', 'processor', ['processor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('order_product_combo_id_fkey', 'order_product', 'combo_amplifier', ['combo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_product', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_guitar_id_fkey', 'order_product', 'guitar', ['guitar_id'], ['id'])
    op.create_foreign_key('order_product_order_id_fkey', 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_product_effect_id_fkey', 'order_product', 'effect_pedal', ['effect_id'], ['id'])
    op.create_foreign_key('order_product_combo_id_fkey', 'order_product', 'combo_amplifier', ['combo_id'], ['id'])
    op.create_foreign_key('order_product_processor_id_fkey', 'order_product', 'processor', ['processor_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_product_combo_id_fkey', 'cart_product', 'combo_amplifier', ['combo_id'], ['id'])
    op.create_foreign_key('cart_product_effect_id_fkey', 'cart_product', 'effect_pedal', ['effect_id'], ['id'])
    op.create_foreign_key('cart_product_processor_id_fkey', 'cart_product', 'processor', ['processor_id'], ['id'])
    op.create_foreign_key('cart_product_guitar_id_fkey', 'cart_product', 'guitar', ['guitar_id'], ['id'])
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
