"""add_m2m_category_attributes

Revision ID: faa5731b7ef1
Revises: 450c33ed26a5
Create Date: 2026-06-20 16:57:50.476959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa5731b7ef1'
down_revision: Union[str, None] = '450c33ed26a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_attributes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id')
    )
    op.drop_constraint('attributes_category_id_fkey', 'attributes', type_='foreignkey')
    op.drop_column('attributes', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('attributes_category_id_fkey', 'attributes', 'category', ['category_id'], ['id'])
    op.drop_table('category_attributes')
    # ### end Alembic commands ###
