name: Testing of project

on:
  push:
    branches: [ "dev2" ]
  pull_request:
    branches: [ "dev2", "dev" ]

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: ilshat_db

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Python install
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Create or update .env file
      run: |
        if [ ! -f .env ]; then
          echo "DB_USER=${{ env.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
          echo "DB_HOST=test_postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=test_db" >> .env
          echo ".env file created"
        else
          echo ".env file already exists, updating values"
          sed -i "s/DB_USER=.*/DB_USER=${{ env.DB_USER }}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ env.DB_PASSWORD }}/" .env
          sed -i "s/DB_HOST=.*/DB_HOST=test_postgres/" .env
          sed -i "s/DB_PORT=.*/DB_PORT=5432/" .env
          sed -i "s/DB_NAME=.*/DB_NAME=test_db/" .env
        fi
        
        echo "Generated .env content."
        cat .env

    - name: Cache PostgreSQL setup
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib/postgresql
          /var/lib/postgresql
        key: ${{ runner.os }}-postgresql-16

    - name: Debug project structure
      run: |
        echo "Текущая структура проекта:"
        ls -la
        echo "Содержимое alembic.ini:"
        cat alembic.ini || echo "alembic.ini не найден"

    - name: Prepare test environment
      run: |
        mkdir -p test_pgdata
        chmod 777 test_pgdata

    - name: Launch test database
      run: |
        docker compose -f docker-compose.test.yml up test_postgres -d

    - name: Run migrations
      run: alembic upgrade head

    - name: Verify migrations
      run: |
        PGPASSWORD="${{ env.DB_PASSWORD }}" psql -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }} -c "\dt"

    - name: Edit .env file 2
      run: |
        sed -i "s/DB_HOST=.*/DB_HOST=test_postgres/" .env
        sed -i "s/DB_PORT=.*/DB_PORT=5432/" .env
        cat .env

    - name: Run tests
      run: |
        sudo docker compose -f docker-compose.test.yml up test_backend --build