name: Testing of project

on:
  push:
    branches: [ "dev2" ]
  pull_request:
    branches: [ "dev2", "dev" ]

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: test_postgres
  DB_PORT: 5432
  DB_NAME: test_db

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Python install
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Create or update .env file
      run: |
        if [ ! -f .env ]; then
          echo "DB_USER=${{ env.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
          echo "DB_HOST=test_postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=test_db" >> .env
          echo "REDIS_HOST=test_redis" >> .env
          echo ".env file created"
        else
          echo ".env file already exists, updating values"
          sed -i "s/DB_USER=.*/DB_USER=${{ env.DB_USER }}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ env.DB_PASSWORD }}/" .env
          sed -i "s/DB_HOST=.*/DB_HOST=test_postgres/" .env
          sed -i "s/DB_PORT=.*/DB_PORT=5432/" .env
          sed -i "s/DB_NAME=.*/DB_NAME=test_db/" .env
          sed -i "s/REDIS_HOST=.*/REDIS_HOST=test_redis/"
        fi
        
        echo "Generated .env content."
        cat .env

    - name: Cache PostgreSQL setup
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib/postgresql
          /var/lib/postgresql
        key: ${{ runner.os }}-postgresql-16

    - name: Debug project structure
      run: |
        echo "Текущая структура проекта:"
        ls -la
        echo "Содержимое alembic.ini:"
        cat alembic.ini || echo "alembic.ini не найден"

    - name: Prepare test environment
      run: |
        mkdir -p test_pgdata
        chmod 777 test_pgdata
        mkdir -p test_redis_data
        chmod 777 test_redis_data

    - name: Launch test database
      run: |
        docker compose -f docker-compose.test.yml up -d test_postgres

    - name: Launch test redis
      run: |
        docker compose -f docker-compose.test.yml up -d test_redis

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          if docker compose -f docker-compose.test.yml exec test_postgres pg_isready -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }}; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL... Attempt $i/10"
          sleep 5
        done

    - name: Run migrations
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5433
        DB_NAME: test_db
      run: |
        # Проверяем подключение перед миграциями
        sed -i "s/DB_HOST=.*/DB_HOST=localhost/" .env
        sed -i "s/DB_PORT=.*/DB_PORT=5433/" .env
        cat .env
        echo ${{ env.DB_HOST }}
        echo ${{ env.DB_PORT }}
        PGPASSWORD="${{ env.DB_PASSWORD }}" psql -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }} -c "SELECT 1"
        alembic upgrade head

    - name: Verify migrations
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5433
        DB_NAME: test_db
      run: |
        PGPASSWORD="${{ env.DB_PASSWORD }}" psql -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }} -c "\dt"

    - name: Edit .env file 2
      run: |
        sed -i "s/DB_HOST=.*/DB_HOST=test_postgres/" .env
        sed -i "s/DB_PORT=.*/DB_PORT=5432/" .env
        cat .env

    - name: Run tests
      run: |
        sudo docker compose -f docker-compose.test.yml up test_backend --build